packages:
  - packages/*
  - templates
  - "!templates/base-*"
  - "!packages/chrome-extension"
  - "!packages/flyio-ssh-proxy"
  - "!packages/replicator"
  - "!packages/replicator-git-sync"
  - "!packages/screenshot-api"
patchedDependencies:
  "@daytonaio/sdk": patches/@daytonaio__sdk.patch
  ai: patches/ai.patch
