packages:
  - packages/*
  - templates
  # - "!templates"
  - "!templates/base-*"
  - "!packages/chrome-extension"
  - "!packages/flyio-ssh-proxy"
  - "!packages/replicator"
  - "!packages/replicator-git-sync"
patchedDependencies:
  "@daytonaio/sdk": patches/@daytonaio__sdk.patch
