FROM docker.io/cloudflare/sandbox:0.3.2

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-pip git ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir git-remote-s3
RUN corepack enable

ARG SQUASH_CLI_VERSION=0.0.5
RUN npm install -g @squashai/cli@$SQUASH_CLI_VERSION

# WORKDIR /root
# COPY templates/base-vite-ts/package.json .
# COPY templates/base-vite-ts/pnpm-lock.yaml .

# RUN pnpm install

ENV PORT=65535
