FROM node:20-alpine

RUN apk add --no-cache python3 py3-pip git bash \
 && pip3 install --break-system-packages --no-cache-dir git-remote-s3 \
 && corepack enable

ARG SQUASH_CLI_VERSION=0.0.9-alpha.1
RUN npm install -g @squashai/cli@$SQUASH_CLI_VERSION

WORKDIR /repo

COPY package.json .
COPY pnpm-lock.yaml .

RUN pnpm install
RUN rm -rf package.json pnpm-lock.yaml
RUN git init

ENV PORT=5173
