# syntax=docker/dockerfile:1.6
###############################################################################
# 1) Build stage – compiles native add-ons & installs global CLIs
###############################################################################
ARG NODE_VERSION=20
FROM node:${NODE_VERSION}-bookworm-slim AS build

# Minimal packages for native-add-on compilation & scripting
RUN apt-get update && apt-get install -y --no-install-recommends \
      git                   \
      python3 python3-pip   \
      bash                  \
      build-essential       \
  && rm -rf /var/lib/apt/lists/*

# Install git-remote-s3
RUN pip3 install --break-system-packages --no-cache-dir git-remote-s3

# Activate Corepack (pnpm / yarn)
RUN corepack enable
# RUN corepack prepare pnpm@ --activate
ENV V8_COMPILE_CACHE_CACHE_DIR=/tmp/v8-compile-cache

ARG SQUASH_CLI_VERSION=latest
RUN npm i -g @squashai/cli@$SQUASH_CLI_VERSION

# -------- Project dependencies --------
WORKDIR /repo
COPY package.json pnpm-lock.yaml wrangler.json ./
RUN pnpm install --frozen-lockfile
RUN rm -rf package.json pnpm-lock.yaml wrangler.json

ENV PORT=5173
